import * as THREE from 'three';import './style.css';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc9e8);scene.fog=new THREE.Fog(0x9fc9e8,700,4200);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.5,10000);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdff2ff,0x405060,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-500,1200,300);scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(7000,7000),new THREE.MeshStandardMaterial({color:0x789a68}));ground.rotation.x=-Math.PI/2;scene.add(ground);
const city=new THREE.Group();scene.add(city);const normal=new THREE.MeshStandardMaterial({color:0xb9b7ae}),tall=new THREE.MeshStandardMaterial({color:0x70757a});
const blocks=[[-140,-160,90,90,180],[0,-170,75,105,260],[130,-150,95,95,210],[-210,-20,80,110,130],[-70,-20,100,90,310],[70,-15,80,110,220],[190,-5,100,90,150],[-170,130,110,85,240],[-35,130,85,95,190],[90,125,110,80,360],[220,135,80,90,175],[-240,270,80,100,110],[-115,270,100,85,155],[20,270,90,90,125],[140,270,95,90,190]];
for(const b of blocks){const [x,z,w,d,h]=b;const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),h>280?tall:normal);m.position.set(x,h/2,z);m.userData.height=h;city.add(m)}
const water=new THREE.Mesh(new THREE.PlaneGeometry(1800,900),new THREE.MeshStandardMaterial({color:0x4c91b0}));water.rotation.x=-Math.PI/2;water.position.set(950,.5,-20);scene.add(water);
const coins:THREE.Mesh[]=[];for(let i=0;i<18;i++){const c=new THREE.Mesh(new THREE.TorusGeometry(7,2.2,8,16),new THREE.MeshStandardMaterial({color:0xffd447,metalness:.4}));const t=i/17;c.position.set(-430+t*780,360-t*170,-650+t*760);c.rotation.y=Math.PI/2;scene.add(c);coins.push(c)}
const glider=new THREE.Group();const wing=new THREE.Mesh(new THREE.ConeGeometry(20,70,3),new THREE.MeshStandardMaterial({color:0x20252b}));wing.rotation.z=Math.PI/2;glider.add(wing);const pilot=new THREE.Mesh(new THREE.SphereGeometry(5,12,8),new THREE.MeshStandardMaterial({color:0xf1c6a5}));pilot.position.y=-7;glider.add(pilot);scene.add(glider);
let pos=new THREE.Vector3(-430,520,-720),vel=new THREE.Vector3(18,-10,30),alive=true,score=0;const input={x:0,y:0,active:false};
const hud=document.createElement('div');hud.id='hud';hud.innerHTML='<strong>CITY GLIDER</strong><span id="stats">Sydney prototype</span>';document.body.appendChild(hud);
const message=document.createElement('div');message.id='message';message.innerHTML='<strong>GLIDE TEST</strong><small>Steer with the pad. Collect gold rings.</small>';document.body.appendChild(message);
const pad=document.createElement('div');pad.id='pad';pad.innerHTML='<div id="stick"></div>';document.body.appendChild(pad);const stick=document.querySelector('#stick') as HTMLElement;
function steer(px:number,py:number){const r=pad.getBoundingClientRect(),max=r.width*.34,dx=THREE.MathUtils.clamp(px-r.left-r.width/2,-max,max),dy=THREE.MathUtils.clamp(py-r.top-r.height/2,-max,max);input.x=dx/max;input.y=dy/max;input.active=true;stick.style.transform='translate('+dx+'px,'+dy+'px)'}
function clear(){input.x=input.y=0;input.active=false;stick.style.transform='translate(0,0)'}
pad.addEventListener('pointerdown',e=>{pad.setPointerCapture(e.pointerId);steer(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(input.active)steer(e.clientX,e.clientY)});pad.addEventListener('pointerup',clear);pad.addEventListener('pointercancel',clear);
function reset(){pos.set(-430,520,-720);vel.set(18,-10,30);score=0;alive=true;coins.forEach(c=>c.visible=true);message.innerHTML='<strong>GLIDE TEST</strong><small>Steer with the pad. Collect gold rings.</small>'}
message.addEventListener('pointerdown',reset);const clock=new THREE.Clock();
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033);if(alive){vel.x+=input.x*22*dt;vel.y+=(-13-input.y*16)*dt;vel.z+=12*dt;vel.multiplyScalar(Math.pow(.995,dt*60));pos.addScaledVector(vel,dt);glider.position.copy(pos);glider.rotation.z=-input.x*.35;glider.rotation.x=input.y*.25;camera.position.lerp(pos.clone().add(new THREE.Vector3(0,55,115)),1-Math.pow(.001,dt));camera.lookAt(pos.clone().add(vel.clone().multiplyScalar(1.2)));for(const c of coins){c.rotation.z+=dt*3;if(c.visible&&c.position.distanceTo(pos)<24){c.visible=false;score++}}let crash=pos.y<=3;for(const b of city.children)if(Math.abs(pos.x-b.position.x)<45&&Math.abs(pos.z-b.position.z)<45&&pos.y<(b.userData.height??100)+8)crash=true;if(crash){alive=false;message.innerHTML='<strong>RUN ENDED</strong><small>'+score+' coins · Tap to restart</small>'}const s=document.querySelector('#stats');if(s)s.textContent='Sydney prototype · '+score+' coins · altitude '+Math.max(0,Math.round(pos.y))+'m'}renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate();